# Generated by Django 5.2.4 on 2025-08-16 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Users",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("First_name", models.CharField(max_length=50)),
                ("Last_name", models.CharField(max_length=50)),
                ("Email", models.EmailField(max_length=254, unique=True)),
                ("Password", models.CharField(max_length=20)),
                ("subscribed_to_newsletter", models.BooleanField(default=False)),
                ("agreed_to_terms", models.BooleanField(default=False)),
            ],
        ),
    ]
